services:
  db:
    image: postgres:17
    container_name: postgres_dev
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_app
    depends_on:
      - db
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - .:/usr/src/app:cached          # ✅ migliora performance su macOS
      - /usr/src/app/node_modules      # ✅ evita override da node_modules locale
    tty: true                          # ✅ utile per il reload live di ts-node-dev
    stdin_open: true                   # ✅ utile per debugging interattivo

volumes:
  dbdata:
