FROM node:20-alpine

WORKDIR /usr/src/app

# Copia solo i file di dipendenze
COPY package.json package-lock.json ./

# Forza l'installazione pulita ogni volta che i file cambiano
RUN npm ci

# Poi copia il resto del codice
COPY . .

# Avvia l'app
CMD ["npm", "run", "start:dev"]
