version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    depends_on:
      - db
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    command: npm run start:dev

volumes:
  dbdata:
